name       : perl-tk
version    : 804.034
release    : 6
source     :
    - https://github.com/eserte/perl-tk/archive/804.034.tar.gz : 3d3cc401e64c8f4b1ed9cb86b3e4e15d89a2ca26ca018d6f5df26bf84a701d74
license    :
    - Artistic-1.0-Perl
    - GPL-2.0
    - TCL
component  : programming.perl
summary    : A graphical user interface toolkit for Perl
description: |
    A graphical user interface toolkit for Perl
builddeps  :
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xft)
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
