name       : perl-tk
version    : '804.036'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz : 32aa7271a6bdfedc3330119b3825daddd0aa4b5c936f84ad74eabb932a200a5e
homepage   : https://metacpan.org/pod/Tk
license    :
    - Artistic-1.0-Perl
    - GPL-2.0-or-later
    - TCL
component  : programming.perl
summary    : A graphical user interface toolkit for Perl
description: |
    A graphical user interface toolkit for Perl
builddeps  :
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(x11)
    - pkgconfig(xft)
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
